[discord]
# Your app id. THIS IS REQUIRED!
app_id = "your_app_id"
# How often the presence updates. Min: 5 | Default: 10
interval = 10

[logger]
# File logger level. Debug logs can get big over time.
# Accepted values:
#   "INFO"
#   "DEBUG"
file_logging_level = "INFO"
console_logging_level = "INFO"

[cover_art]
# This is required to show cover art.
# Get an api key from: https://api.imgbb.com/
imgbb_api_key = "api_key_here"


[player.default]
# Default (and example) player configuration
# Accepted fields:
#   ignore: Ignore (or don't) specified player
#   activity_type: Player specific activity type.
#       "listening"
#       "watching"
#       "playing"
#       "competing"
#
# Use "pymprisence -p" to see current players.
ignore = true
activity_type = "listening"

[player.strawberry]
ignore = false
activity_type = "listening"

[player.firefox]
ignore = true
activity_type = "watching"
